// ---------------------------------------------------------------------------
// reve.ts  (файл сохранён как runware.ts для совместимости с импортами)
// Прямое подключение к Reve 2.0 API — модель с нативным рендерингом текста.
// Docs: https://api.reve.com/v1/image/create
// ---------------------------------------------------------------------------

const REVE_API_KEY = process.env.REVE_API_KEY || '';

const FALLBACK_URL =
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80';

/**
 * Generates a product banner image using the Reve 2.0 API.
 * Reve 2.0 natively renders readable text inside images (TypoGuard engine).
 *
 * @param prompt - Layout-First prompt generated by generateLayoutFirstPrompt()
 * @returns A publicly accessible image URL (data-URL or Reve CDN URL), or a fallback on error.
 */
export async function generateImage(prompt: string): Promise<string> {
  if (!REVE_API_KEY) {
    console.warn('[Reve] REVE_API_KEY is not set. Using fallback placeholder.');
    return FALLBACK_URL;
  }

  try {
    const response = await fetch('https://api.reve.com/v1/image/create', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${REVE_API_KEY}`,
        'Content-Type': 'application/json',
        // Request a direct URL instead of base64 blob
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        prompt,
        aspect_ratio: '16:9',
        // convert_base64_to_url: true — if Reve returns base64, we handle it below
      }),
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      throw new Error(`Reve API error ${response.status}: ${errText}`);
    }

    const result = await response.json();

    // ── Case 1: API returned a direct URL ─────────────────────────────────
    if (result?.url && typeof result.url === 'string') {
      return result.url;
    }

    // ── Case 2: API returned data[].url (OpenAI-compatible format) ────────
    if (Array.isArray(result?.data) && result.data[0]?.url) {
      return result.data[0].url as string;
    }

    // ── Case 3: API returned base64 blob — convert to data-URL ────────────
    const b64 =
      result?.b64_json ||
      result?.data?.[0]?.b64_json ||
      result?.image;

    if (b64 && typeof b64 === 'string') {
      // Detect mime type from base64 prefix, default to jpeg
      const mime = b64.startsWith('/9j/') ? 'image/jpeg' : 'image/png';
      return `data:${mime};base64,${b64}`;
    }

    throw new Error('Reve API returned an unrecognised response structure.');
  } catch (error) {
    console.error('[Reve] Image generation failed:', error);
    return FALLBACK_URL;
  }
}
